### ISSUE TITLE
GoAnimate-Wrapper 

### ISSUE THREAD

**Issue by BattalFaran** [Windows81/GoAnimate-Wrapper#120]
I'm trying to join a GoAnimate-Wrapper, please

**Comment by Windows81** [comment]
Heya.  I haven't updated the codebase in four years.  I want to avoid vandalism and stuff.

Feel free to **fork the repository**, write your own changes, then open a pull request once you're done.

Otherwise, if you have any specific changes to propose, please let other people know.

I will add you to the team once I see your contributions.
